create table
  hotel (
    id bigint generated by default as identity primary key,
    name text null
  );

create table
  employee (
    id bigint generated by default as identity primary key,
    name text null
  );

create table
  booking (
    id bigint generated by default as identity primary key,
    hotel_id bigint not null,
    foreign key (hotel_id) references hotel (id)
  );

create table
  placement (
    id bigint generated by default as identity primary key,
    employee_id bigint not null,
    booking_id bigint not null,
    foreign key (employee_id) references employee (id),
    foreign key (booking_id) references booking (id)
  );

create or replace function hotel(placement) returns setof hotel rows 1 as $$
  select h.* from booking b
  join hotel h on h.id = b.hotel_id
  where b.id = $1.booking_id
$$ stable language sql;

create or replace function placements(hotel) returns setof placement as $$
  select p.* from placement p
  join booking b on b.hotel_id = $1.id
$$ stable language sql;
